Nav bar component
Code-the-Dream-School/cc-prac-team1-front pull request #42
Opened 2023-06-19 04:47 UTC by Maarimar

finish styling

2023-06-19 16:28 UTC, Count-MonteCristo approved these changes

2023-06-19 18:15 UTC, dkprioleau requested changes
A lot of the files you made changes to (lost and found files & icon images) you  made in another PR so you don't need to make them again. They will be added once your other PR is approved.  You're two other PR's need to be merged first since there seems to be an error from the icon files.

2023-06-19 18:15 UTC, dkprioleau commented on src/components/pages/map.js
Remove comments

2023-06-20 12:47 UTC, dkprioleau approved these changes
LGTM, I also noticed the error has disappeared so you can go ahead and merge. I noticed not all the pages have the navbar displaying though: editProfile, selectLorOrFound, addLostPet, addFoundPet. You can either add another commit to this PR or make another issue to add navbar to these pages

2023-06-20 16:28 UTC, Maarimar commented
> LGTM, I also noticed the error has disappeared so you can go ahead and merge. I noticed not all the pages have the navbar displaying though: editProfile, selectLorOrFound, addLostPet, addFoundPet. You can either add another commit to this PR or make another issue to add navbar to these pages

I followed the design we have on Figma :) we can discuss if the navbar goes everywhere during ore next meeting

2023-06-20 16:28 UTC, merged