Labels addpet form
Code-the-Dream-School/cc-prac-team1-front pull request #43
Opened 2023-06-19 04:47 UTC by Maarimar

2023-06-19 16:28 UTC, Count-MonteCristo approved these changes

2023-06-19 17:47 UTC, dkprioleau requested changes
Small changes and then it's good

2023-06-19 17:47 UTC, dkprioleau commented on src/components/pages/AddFoundPet.js
>            <option value={values.animalType}>Other</option>
Just something to think about but if someone chooses other will they be able to specify what animal that is  ie: if it's a turtle, but this can be added functionality later

2023-06-19 17:47 UTC, dkprioleau commented on src/components/pages/AddFoundPet.js
> +        <Label>Color</Label>
I'm not sure if you are making this a separate issue, but don't forget to change color into an input as well (same in lost page)

2023-06-19 17:47 UTC, dkprioleau commented on src/components/pages/map.js
Uncomment this file

2023-06-19 18:04 UTC, Count-MonteCristo commented on src/components/pages/AddFoundPet.js
>            <option value={values.animalType}>Other</option>
I was thinking we could also make that field a simple input field. That way, the user can specify any animal type for their pet.

2023-06-20 12:34 UTC, dkprioleau commented on src/components/pages/AddFoundPet.js
>            <option value={values.animalType}>Other</option>
Yes that's a nice  simple solution!

2023-06-20 16:28 UTC, merged