added icons-pending styling
Code-the-Dream-School/cc-prac-team1-front pull request #44
Opened 2023-06-19 04:48 UTC by Maarimar

2023-06-19 16:28 UTC, Count-MonteCristo approved these changes

2023-06-19 17:22 UTC, dkprioleau requested changes
Please fix the below comment, then it's good to go!

2023-06-19 17:22 UTC, dkprioleau commented on src/components/pages/map.js
Was there a reason to uncomment this whole file? Please uncomment.

2023-06-20 12:29 UTC, dkprioleau approved these changes
LGTM

2023-06-20 16:26 UTC, merged